const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("openhouse", {
  listApps: () => ipcRenderer.invoke("apps:list"),
  openApp: (id, options) => ipcRenderer.invoke("apps:open", id, options),
  getAppStatuses: () => ipcRenderer.invoke("apps:statuses"),
  setAppRunning: (id, shouldRun) => ipcRenderer.invoke("apps:set-running", id, shouldRun),
  onAppsState: (callback) => ipcRenderer.on("apps:state", (_event, value) => callback(value)),
  listTabs: () => ipcRenderer.invoke("tabs:list"),
  openTab: (appId) => ipcRenderer.invoke("tabs:open", appId),
  closeTab: (tabId) => ipcRenderer.invoke("tabs:close", tabId),
  activateTab: (tabId) => ipcRenderer.invoke("tabs:activate", tabId),
  showDesktop: () => ipcRenderer.invoke("tabs:show-desktop"),
  openNewWindow: () => ipcRenderer.invoke("tabs:new-window"),
  getContainerSettings: () => ipcRenderer.invoke("containers:settings"),
  setMaxWebContainers: (value) => ipcRenderer.invoke("containers:set-max", value),
  closeAppWindow: () => ipcRenderer.invoke("app-window:close"),
  onTabsState: (callback) => ipcRenderer.on("tabs:state", (_event, value) => callback(value)),
  onTabsError: (callback) => ipcRenderer.on("tabs:error", (_event, value) => callback(value)),
  getServiceStatuses: () => ipcRenderer.invoke("services:status"),
  getRuntimeStatus: () => ipcRenderer.invoke("runtime:status"),
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  toggleChrome: () => ipcRenderer.invoke("shell:toggle-chrome"),
  setChromeHidden: (hidden) => ipcRenderer.invoke("shell:set-chrome", hidden),
});
